[tool.poetry]
name = "transformer"
version = "0.1.0"
description = ""
authors = ["m.khal <m.khal@outlook.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
